name: Build Flutter APK

on: [push, pull_request, workflow_dispatch]
  

jobs:
  # Todo: perform tests
  build:
    name: Build APK
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set up Java 12
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get app dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk
        
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: APK directory
          path: "build/app/outputs/apk/release/app-release.apk"
